/**
 * Site Configuration Composable
 *
 * Provides reactive access to the site configuration data generated by
 * the site configuration generator script. This composable allows components
 * to access page metadata, navigation data, and site statistics.
 *
 * @example Basic usage
 * ```vue
 * <script setup>
 * const { config, pages, loading, error } = useSiteConfig();
 *
 * // Access all pages
 * console.log(pages.value);
 *
 * // Access only content pages
 * console.log(contentPages.value);
 *
 * // Access site statistics
 * console.log(stats.value);
 * </script>
 * ```
 *
 * @example Manual loading
 * ```vue
 * <script setup>
 * const { loadConfig, config } = useSiteConfig();
 *
 * // Manually trigger config loading
 * await loadConfig();
 * console.log(config.value);
 * </script>
 * ```
 *
 * @author Violence Prevention Plan for Illinois: 2025-2029
 * @version 1.0.0
 */

/**
 * Composable for accessing site configuration at runtime
 *
 * @returns {Object} Site configuration composable object
 */
export const useSiteConfig = () => {
  const config = ref(null);
  const loading = ref(false);
  const error = ref(null);

  /**
   * Load site configuration from the public directory
   *
   * @returns {Promise<Object|null>} Loaded configuration or null on error
   */
  const loadConfig = async () => {
    // Return cached config if already loaded
    if (config.value) return config.value;

    loading.value = true;
    error.value = null;

    try {
      // Try multiple paths for robustness
      const paths = [
        '/config/routes.config.json',
        '/data/routes.config.json'
      ];

      let response;
      for (const path of paths) {
        try {
          response = await $fetch(path);
          break;
        } catch (e) {
          // Continue to next path
          continue;
        }
      }

      if (!response) {
        throw new Error('Routes configuration not found at any expected path');
      }

      config.value = response;

      // Log successful load in development
      if (process.env.NODE_ENV === 'development') {
        console.log('✅ Routes configuration loaded:', {
          totalPages: response.stats?.totalPages || 0,
          contentPages: response.stats?.contentPages || 0,
          vuePages: response.stats?.vuePages || 0,
          generatedAt: response.generatedAt
        });
      }

      return response;
    } catch (e) {
      error.value = e;
      console.error('Failed to load site configuration:', e);
      return null;
    } finally {
      loading.value = false;
    }
  };

  /**
   * Find a page by its path
   *
   * @param {string} path - The page path to search for
   * @returns {Object|null} Found page object or null
   */
  const findPageByPath = (path) => {
    if (!config.value?.pages) return null;
    return config.value.pages.find(page => page.path === path) || null;
  };

  /**
   * Find pages by type
   *
   * @param {string} type - Page type ('content' or 'vue')
   * @returns {Array} Array of pages matching the type
   */
  const findPagesByType = (type) => {
    if (!config.value?.pages) return [];
    return config.value.pages.filter(page => page.type === type);
  };

  /**
   * Get pages that match a pattern
   *
   * @param {RegExp|string} pattern - Pattern to match against page paths
   * @returns {Array} Array of matching pages
   */
  const findPagesByPattern = (pattern) => {
    if (!config.value?.pages) return [];
    const regex = typeof pattern === 'string' ? new RegExp(pattern) : pattern;
    return config.value.pages.filter(page => regex.test(page.path));
  };

  // Auto-load on first access in client-side
  if (import.meta.client && !config.value && !loading.value) {
    loadConfig();
  }

  return {
    // Core reactive state
    config: readonly(config),
    loading: readonly(loading),
    error: readonly(error),

    // Methods
    loadConfig,
    findPageByPath,
    findPagesByType,
    findPagesByPattern,

    // Computed helpers for easy access
    pages: computed(() => config.value?.pages || []),
    contentPages: computed(() => config.value?.pages?.filter(p => p.type === 'content' || (p.sources && p.sources.some(s => s.type === 'content'))) || []),
    vuePages: computed(() => config.value?.pages?.filter(p => p.type === 'vue' || (p.sources && p.sources.some(s => s.type === 'vue'))) || []),
    combinedPages: computed(() => config.value?.pages?.filter(p => p.type === 'combined') || []),
    stats: computed(() => config.value?.stats || {}),
    summary: computed(() => config.value?.summary || {}),
    baseUrl: computed(() => config.value?.baseUrl || ''),
    generatedAt: computed(() => config.value?.generatedAt || null),

    // Utility computed properties
    isLoaded: computed(() => !!config.value),
    hasError: computed(() => !!error.value),
    isLoading: computed(() => loading.value),
    totalPages: computed(() => config.value?.stats?.totalPages || 0)
  };
};
